version: '3.8'
name: stocks

services:
    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        volumes:
            - ./src:/var/www/html
        working_dir: /var/www/html
        container_name: stocks-php
        depends_on:
            - mysql
            - redis
        networks:
            - stocks-network
    redis:
        image: "redis:latest"
        container_name: stocks-redis
        env_file:
            - .env
        ports:
            - "6379:6379"
        environment:
            - REDIS_PASSWORD=${REDIS_PASSWORD}
        volumes:
            - redis_data:/data
        networks:
            - stocks-network
    nginx:
        image: nginx:1.25.0-bullseye
        container_name: stocks-nginx
        ports:
            - '8080:80'
        links:
            - php
        volumes:
            - ./src:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
            - mysql
            - redis
        networks:
            - stocks-network
    mysql:
        image: mysql:8.2.0
        container_name: stocks-mysql
#        command: --default-authentication-plugin=mysql_native_password
        env_file:
            - .env
        tty: true
#        command: ["sh", "-c", "env | grep MYSQL"]
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}

        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
            - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
        networks:
            - stocks-network
volumes:
    redis_data:
    mysql_data:
networks:
    stocks-network:
        driver: bridge
